version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

os: Windows Server 2012

install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv

build_script:
  - mvn clean install -B -Dci
